CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    CONSTRAINT uq_user_email UNIQUE(email)
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(1000),
    requestor_id BIGINT,
    CONSTRAINT fk_requests_to_user
        FOREIGN KEY(requestor_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255),
    description varchar(1000),
    is_available varchar(5),
    owner_id BIGINT,
    request_id BIGINT,
    CONSTRAINT fk_items_to_user
        FOREIGN KEY(owner_id) REFERENCES users(id),
    CONSTRAINT fk_items_to_request
        FOREIGN KEY(request_id) REFERENCES requests(id)

)